KEYPOINTS =[
  {"point": [60, 100], "label": "white_pitcher_spout"},
  {"point": [210, 80], "label": "white_pitcher_handle"},
  {"point": [70, 200], "label": "red_box_top_left"},
  {"point": [120, 430], "label": "red_box_bottom_right"},
  {"point": [240, 110], "label": "cardboard_box_top_left"},
  {"point": [450, 320], "label": "cardboard_box_bottom_right"},
  {"point": [265, 190], "label": "duck_beak"},
  {"point": [290, 160], "label": "duck_head"},
  {"point": [350, 140], "label": "duck_body"},
  {"point": [420, 130], "label": "duck_tail"},
  {"point": [410, 190], "label": "duck_left_foot"},
  {"point": [435, 220], "label": "duck_right_foot"},
  {"point": [280, 340], "label": "orange_tray_top_left"},
  {"point": [430, 530], "label": "orange_tray_bottom_right"},
  {"point": [435, 435], "label": "orange_tray_handle_hole"},
  {"point": [20, 520], "label": "yellow_toy_top_handle"},
  {"point": [45, 640], "label": "yellow_toy_face_center"},
  {"point": [80, 600], "label": "yellow_toy_right_eye"},
  {"point": [900, 50], "label": "power_adapter_top_left"},
  {"point": [950, 270], "label": "power_adapter_green_led"},
  {"point": [990, 320], "label": "power_adapter_bottom_right"},
  {"point": [680, 550], "label": "cable_coil_left_edge"},
  {"point": [830, 580], "label": "cable_coil_right_edge"},
  {"point": [760, 650], "label": "green_storage_box_top_left"}
]